#define TEXTURE_BOB 0
#define TEXTURE_GARY 1
#define TEXTURE_GRASS 2
#define TEXTURE_GRASS32 3
#define TEXTURE_ISAAC 4
#define TEXTURE_ROCK32 5
#define TEXTURE_TILE 6
#define TEXTURE_TILE32 7
#define TEXTURE_TILELEFTDOWN 8
#define TEXTURE_TILELEFTUP 9
#define TEXTURE_TILERIGHTDOWN 10
#define TEXTURE_TILERIGHTUP 11
#define TEXTURE_WATER 12

#define FONT_CHUNKFIVE_EX 0


