#ifndef DEFINE_HPP
# define DEFINE_HPP

# define EMPTY				"EMPTY"
# define HOST_NAME			"HOST_NAME"
# define USER_NAME			"USER_NAME"
# define OSX_NAME			"OSX_NAME"
# define OSX_VERSION		"OSX_VERSION"
# define OSX_BUILD			"OSX_BUILD"
# define KERNEL_VERSION		"KERNEL_VERSION"
# define TIME				"TIME"
# define DATE				"DATE"
# define CURRENT_RAM		"CURRENT_RAM"
# define MAX_RAM			"MAX_RAM"
# define CPU_NAME			"CPU_NAME"
# define CPU_NBPROCESSOR	"CPU_NBPROCESSOR"
# define CPU_CURTASKS		"CPU_CURTASKS"
# define CPU_CURTHREAD		"CPU_CURTHREAD"
# define CPU_USAGE			"CPU_USAGE"
# define CPU_LOADAVERAGE	"CPU_LOADAVERAGE"
# define CPU_MATCHFACTOR	"CPU_MATCHFACTOR"

# define KEY_ESCAPE			27

#endif
