<?php

namespace philemon\ModuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityLoginRepository extends EntityRepository
{
	function getActivities($module_id, $user_id)
	{
		return $this->createQueryBuilder('al')
					->leftJoin('al.activity', 'a')
					->leftJoin('al.user', 'u')
					->where('u.id=:id AND a.module=:mid')
					->setParameter('id', $user_id)
					->setParameter('mid', $module_id)
					->getQuery()
					->getResult();
	}

	function isRegister($user_id, $activity_id)
	{
		$res = $this->createQueryBuilder('a')
					->leftJoin('a.activity', 'm')
					->leftJoin('a.user', 'u')
					->where('u.id=:id AND m.id=:mid')
					->setParameter('id', $user_id)
					->setParameter('mid', $activity_id)
					->getQuery()
					->getResult();
		if (count($res) > 0)
			return true;
		return false;
	}

	function getPeer($id, $activity_id){
		return $this->createQueryBuilder('fp')
					->leftJoin('fp.activity', 'm')
					->leftJoin('fp.user', 'u')
					->where('u.id!=:id AND m.id=:mid')
					->setParameter('id', $id)
					->setParameter('mid', $activity_id)
					->getQuery()
					->getResult();
	}
}
