<?php

namespace philemon\ModuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
  function selectAll()
  {
    return $this->createQueryBuilder('a')
    					->getQuery()
    					->getResult();
  }

  function selectUnsubModules($subs, $user_id)
  {
	$ids = array();
	if (count($subs) <= 0)
	{
		return $this->createQueryBuilder('m')
					->getQuery()
					->getResult();
	}
	foreach ($subs as $s)
		$ids[] = $s->getModule()->getId();
	return $this->createQueryBuilder('m')
				->where('m.id NOT IN ('.implode(',', $ids).')')
				->getQuery()
				->getResult();
  }
}
