<?php

namespace philemon\ModuleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleLoginRepository extends EntityRepository
{
  function selectSubModules($user_id)
  {
    return $this->createQueryBuilder('a')
				->leftJoin('a.module', 'm')
				->leftJoin('a.user', 'u')
				->where('u.id=:id')
				->setParameter('id', $user_id)
				->getQuery()
				->getResult();
  }

	function isRegister($user_id, $module_id)
	{
		$res = $this->createQueryBuilder('a')
					->leftJoin('a.module', 'm')
					->leftJoin('a.user', 'u')
					->where('u.id=:id AND m.id=:mid')
					->setParameter('id', $user_id)
					->setParameter('mid', $module_id)
					->getQuery()
					->getResult();
		if (count($res) > 0)
			return true;
		return false;
	}
}
