imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @philemonUserBundle/Resources/config/admin.yml }
    - { resource: @philemonModuleBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: philemon\UserBundle\Entity\User
        entity_managers:
            default:
                mappings:
                    HackzillaTicketBundle: ~
                    FOSUserBundle: ~
                    philemonModuleBundle: ~
                    philemonFtCalendarBundle: ~
                    BladeTesterCalendarBundle: ~
                    philemonUserBundle:
                        mapping:              true
                        type:                 annotation
                        alias:                ~
                        prefix:               philemon\UserBundle\Entity
                        is_bundle:            true
                    CCDNForumForumBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNForum\ForumBundle\Entity
                        is_bundle:            true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    philemon\UserBundle\Entity\User # La classe de l'entité User que nous utilisons

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:      Philemon admin
    title_logo: bundles/philemonuser/images/user4.png

fr3d_ldap:
    driver:
        host: ldap.42.fr
        port: 389
    user:
        baseDn: ou=2013,ou=people,dc=42,dc=fr
        filter: (&(ObjectClass=Top))
        attributes:
            - { ldap_attr: uid, user_method: setUsername }
            - { ldap_attr: alias, user_method: setEMail }
            - { ldap_attr: cn, user_method: setName }
            - { ldap_attr: uidnumber, user_method: setNbuid }

blade_tester_calendar:
    driver: doctrine/orm
    engine: twig
    classes:
        event:
            entity: philemon\FtCalendarBundle\Entity\Event
        category:
            entity: BladeTester\CalendarBundle\Entity\EventCategory
